### PR TITLE
Completely remade!

### PR DESCRIPTION
**Pull request by mbrkhrdt**
Since this is a remake, there will be a pretty lengthy comment.

I have completely remade the DC24 Bot in JavaScript! This is because the old bot was no longer being maintained, and was hard to edit. This new bot contains the same features as the old one, but more efficient.

This includes:
--Error Lookup (Although the database needs contributions)
--Mail Code Sharing
--DNS lookup
--Patchers lookup

And potentially more coming in the future! I hope this can serve as the new DC24 bot, with many updates to come in the future.

### CODE REVIEW

**Comment by yeah-its-gloria** [comment]
JavaScript





why does nobody make a bot in another language these days

**Comment by mbrkhrdt** [comment]
i knew someone was gonna say that

**Comment by yeah-its-gloria** [comment]
indeed

~~When C# edition~~

**Comment by mbrkhrdt** [comment]
¯\_(ツ)_/¯

**Comment by yeah-its-gloria** [comment]
Doesn't look bad tho :P

**Comment by MikeModder** [comment]
Not a maintainer but is there anywhere we can see this bot in action? 

I also find it unlikely that a complete switch of languages will be easily accepted. How is this "more efficient"?

I personally don't see anything that's particularly great about this new code, and actually have a few things that I think should be done differently, namely the storing of codes. I don't think writing codes to a plain JSON file is the best idea. Based on my quick look through, it will actually begin to slow down code retrieval as the JSON file is loaded and then parsed every time the code command is run.

**Comment by MikeModder** [comment]
Also, please figure out how to sqaush commits or something 😃

**Comment by spotlightishere** [comment]
Seconded on the above - I think this was via GitHub web, using GitHub Desktop or the like will help a ton.

**Comment by mbrkhrdt** [comment]
The only reason I made this was because it was an obsolete version of RiiConnect24 bot. Its more efficient because theres config.json which allows easy setting changes. Also, most of the commands on the old DC24 bot just said soon:tm: so this was needed regardless

**Comment by mbrkhrdt** [comment]
In terms of seeing it in action, you can do so in this server: https://discord.gg/aGWrJXK

**Pull request closed without merging**
